### ISSUE TITLE
Merge the applicable sections from Exploration of MoQ scenarios and Data Model draft into this draft

### ISSUE THREAD

**Issue by SpencerDawkins** [moq-wg/moq-requirements#102]
Based on review comments from @aboba on the mailing list [here](https://mailarchive.ietf.org/arch/msg/moq/L_sCmyaHC7fBXDc3FMcntlJOLec/).

**Comment by SpencerDawkins** [comment]
Draft is in suhasHere/moq-drafts.

**Comment by fluffy** [comment]
Awesome - let me know if something I can do to help

**Comment by suhasHere** [comment]
Thanks @SpencerDawkins  .. look forward to the updates. +1 to @fluffy , please let me know if we can be of any help
