### ISSUE TITLE
Support advertising insertion 

### ISSUE THREAD

**Issue by wilaw** [moq-wg/moq-requirements#108]
MoQ Transport, in combination with a MoQ Streaming Format, needs to support mechanisms to allow ad insertion. This ad insertion:

- Should be compliant with current IAB and SCTE  standards such as 
    - SCTE-35,  which specifies signals that can be used to identify advertising breaks, advertising content, and programming content.
    - VAST (Video Ad Serving Template)
    - VPAID (Video Player Ad-serving Interface Definition)
    - VMAP (Video Multiple Ad Playlist)
- Should be able to participate in both server-side and client side ad insertion schemes. The server-side solution may have a mode in which the ad  is stitched seamlessly into the primary content and the ad boundaries are indistinguishable to the client. 
- Should be dynamic in nature, allowing for just-in-time decisions to be made for choosing which content to insert. 
- Should allow access to, and compatibility with,  a subset of existing ad inventory.

**Comment by fiestajetsam** [comment]
Some of my initials thoughts:
* To stick to the separation model of "church and state", we should also have agility to support more than SCTE-35/IAB specs in the transport layer
* Is it required that _all_ streaming formats must support event tracks? Or is the requirement here that just the transport through the catalog enables it?
* Is there a benefit to describing these requirements more generically - although enabling advertising for live broadcast is clearly the obvious use case having this functionality could be useful for other reasons, such as:
  * In teleconferencing, a presenter switching one (or all) viewer's video to a different source such as the slide show or the presenters camera
  * Falling viewers over to another source when the current one ends e.g Twitch's "raiding"

**Comment by fiestajetsam** [comment]
Given the PR above is merged, I'm closing this noting the above issue on ingest will carry on.
