### ISSUE TITLE
Use Cases for H3 media transport?

### ISSUE THREAD

**Issue by SpencerDawkins** [moq-wg/moq-requirements#79]
From [the MOQ charter](https://datatracker.ietf.org/wg/moq/about/): 

> Media will be mapped onto underlying QUIC mechanisms (QUIC streams and/or QUIC datagrams) and **can be used over raw QUIC or WebTransport**.

Just checking - is anyone expecting to use MOQ over H3, but not using WebTransport? That could be fine, but it seems worth verifying early in the process.

**Comment by SpencerDawkins** [comment]
[kixelated](https://github.com/fiestajetsam/draft-gruessing-moq-requirements/issues?q=is%3Aissue+is%3Aopen+author%3Akixelated) started a [LONG and helpful thread about this,](https://mailarchive.ietf.org/arch/msg/moq/S3eOPU5XnvQ4kn1zJyDThG5U4sA/) on the MOQ mailing list.

This issue started off about verifying whether we needed to support HTTP/3 as a transport, as well as WebTransport and QUIC. 

I think this issue in the requirements draft is more reasonably, "what can you do with HTTP/3 transport, that is difficult, unreasonable, or impossible to do with WebTransport or QUIC?.

**Comment by aboba** [comment]
I'd suggest that the question is turned around: "what use cases can you address with WebTransport or QUIC" that is difficult, unreasonable or impossible to do with HTTP/3"?  Some thoughts on what those might be: 

1.  Use cases benefitting from frame/stream transport. HTTP/3 can transport of groups of frames which depend on each other within a single QUIC stream.  However, AFAICT it cannot respond with multiple streams, each containing a single frame.
2.  Use cases that require support for partial reliability on the receiver.  In RoQ we've discussed the ambiguity created when a receiver sends  STOP_SENDING when there are multiple frames/stream.  The same considerations would apply to HTTP/3, which cannot support frame/stream transport.  So if HTTP/3 were to support partial reliability, it would have to do so on the sender.

**Comment by SpencerDawkins** [comment]
@fiestajetsam agrees with @aboba and doesn't see a use case applicable at this moment in our current thinking.

I agree with @fiestajetsam and @aboba, and would add that the use cases @aboba did conjure up came with challenges to fulfill the use cases. 

I opened this issue for completeness, so since no one has provided either 

> "what use cases can you address with HTTP/3 transport, that is difficult, unreasonable, or impossible to do with WebTransport or QUIC?.

or

>  "what use cases can you address with WebTransport or QUIC that is difficult, unreasonable or impossible to do with HTTP/3"

I'm comfortable closing this one, but will tag @iansweat in case he either 

1. disagrees, or 
2. thinks this is relevant for the [MOQT](https://moq-wg.github.io/moq-transport/draft-ietf-moq-transport.html) draft.

**Comment by ianswett** [comment]
Thanks for closing this!
